package Huffmanodevi.java;
import java.util.PriorityQueue;
import java.util.Scanner;
import java.util.Comparator;
 
class Huffmanodevi {
 
    public static void printCode(Huffman root, String s)
    {
 
        // base case; if the left and right are null
        // then its a leaf node and we print
        // the code s generated by traversing the tree.
        if (root.left
                == null
            && root.right
                   == null
            && Character.isLetter(root.c)) {
 
            // c is the character in the node
            System.out.println(root.c + ":" + s);
 
            return;
        }
 
    
        printCode(root.left, s + "0");
        printCode(root.right, s + "1");
    }
 
   
    public static void main(String[] args)
    {
 
        Scanner s = new Scanner(System.in);
 
        int n = 6;
        char[] charArray = { 'a', 'b', 'c', 'd', 'e', 'f' };
        int[] charfreq = { 5, 9, 12, 13, 16, 45 };
 
 
        PriorityQueue<Huffman> q
            = new PriorityQueue<Huffman>(n, new MyComparator());
 
        for (int i = 0; i < n; i++) {
 
            Huffman hn = new Huffman();
 
            hn.c = charArray[i];
            hn.data = charfreq[i];
 
            hn.left = null;
            hn.right = null;
 
            q.add(hn);
        }
 
        Huffman root = null;
 
   
        while (q.size() > 1) {
 
         
            Huffman x = q.peek();
            q.poll();
 
          
            Huffman y = q.peek();
            q.poll();
 
            Huffman f = new Huffman();
 
          
            f.data = x.data + y.data;
            f.c = '-';
 
            f.left = x;
 
            
            f.right = y;
 
          
            root = f;
 
            q.add(f);
        }
 
      
        printCode(root, "");
        System.out.println("--------------------");
        System.out.println("'abcdef' = '110011011001011110'");
        System.out.println("--------------------");
    }
}
 

class Huffman {
 
    int data;
    char c;
 
    Huffman left;
    Huffman right;
}
 

class MyComparator implements Comparator<Huffman> {
    public int compare(Huffman x, Huffman y)
    {
 
        return x.data - y.data;
    }
   
}
 